
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-multitenancy-kmdkuk-com-v1-tenant
  failurePolicy: Fail
  name: mtenant.kb.io
  rules:
  - apiGroups:
    - multitenancy.kmdkuk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multitenancy-kmdkuk-com-v1-tenant
  failurePolicy: Fail
  name: vtenant.kb.io
  rules:
  - apiGroups:
    - multitenancy.kmdkuk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
